function ork_create_plant_block(modelName)
%ORK_CREATE_PLANT_BLOCK  Create a masked Simulink library block for OR import.
%
%   ORK_CREATE_PLANT_BLOCK() creates a new Simulink library 'ork_plant_lib'
%   containing a masked subsystem that automatically imports .ork data.
%
%   ORK_CREATE_PLANT_BLOCK(MODELNAME) uses the specified library name.
%
%   The masked block provides these mask parameters:
%     - ork_file_path: Path to the .ork file
%     - sim_index: Simulation index (0-based, default 0)
%     - mach_max, aoa_max_deg: Aero table extents
%     - enable_validation: Run OR sim for comparison
%
%   The mask initialization callback calls ork_import() and populates the
%   mask workspace. The block's output ports expose the imported data via
%   lookup tables.
%
%   Usage:
%     1. Run this script to create the library
%     2. Copy the 'ORK Plant Loader' block into your model
%     3. Double-click the block and set the .ork file path
%     4. Run your simulation — data loads automatically
%
%   See also: ork_import, ork_setup_plant

    if nargin < 1
        modelName = 'ork_plant_lib';
    end

    %% Create the library
    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end
    new_system(modelName, 'Library');
    open_system(modelName);

    %% Create the masked subsystem
    blkPath = [modelName, '/ORK Plant Loader'];
    add_block('simulink/Ports & Subsystems/Subsystem', blkPath);

    % Remove default content
    delete_line(blkPath, 'In1/1', 'Out1/1');
    delete_block([blkPath, '/In1']);
    delete_block([blkPath, '/Out1']);

    %% Add output ports and lookup tables inside the subsystem

    % -- Simulation Clock Input (uses simulation time) --
    add_block('simulink/Sources/Clock', [blkPath, '/Clock'], ...
        'Position', [50, 30, 90, 50]);

    % -- Thrust Lookup Table (1-D: time → thrust) --
    add_block('simulink/Lookup Tables/1-D Lookup Table', [blkPath, '/Thrust_LUT'], ...
        'Position', [180, 20, 280, 60], ...
        'Table', 'thrust_force', ...
        'BreakpointsForDimension1', 'thrust_time', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Clock/1', 'Thrust_LUT/1');

    % -- Mass Lookup Table (1-D: time → mass) --
    add_block('simulink/Lookup Tables/1-D Lookup Table', [blkPath, '/Mass_LUT'], ...
        'Position', [180, 80, 280, 120], ...
        'Table', 'mass_total', ...
        'BreakpointsForDimension1', 'mass_time', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Clock/1', 'Mass_LUT/1');

    % -- Ixx Lookup Table --
    add_block('simulink/Lookup Tables/1-D Lookup Table', [blkPath, '/Ixx_LUT'], ...
        'Position', [180, 140, 280, 180], ...
        'Table', 'Ixx_vs_time', ...
        'BreakpointsForDimension1', 'mass_time', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Clock/1', 'Ixx_LUT/1');

    % -- Iyy Lookup Table --
    add_block('simulink/Lookup Tables/1-D Lookup Table', [blkPath, '/Iyy_LUT'], ...
        'Position', [180, 200, 280, 240], ...
        'Table', 'Iyy_vs_time', ...
        'BreakpointsForDimension1', 'mass_time', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Clock/1', 'Iyy_LUT/1');

    % -- Izz Lookup Table --
    add_block('simulink/Lookup Tables/1-D Lookup Table', [blkPath, '/Izz_LUT'], ...
        'Position', [180, 260, 280, 300], ...
        'Table', 'Izz_vs_time', ...
        'BreakpointsForDimension1', 'mass_time', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Clock/1', 'Izz_LUT/1');

    % -- CG Lookup Table --
    add_block('simulink/Lookup Tables/1-D Lookup Table', [blkPath, '/CG_LUT'], ...
        'Position', [180, 320, 280, 360], ...
        'Table', 'cg_x_vs_time', ...
        'BreakpointsForDimension1', 'mass_time', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Clock/1', 'CG_LUT/1');

    % -- 2-D CD Lookup (Mach × AoA) --
    % Inputs: Mach (In1) and AoA (In2)
    add_block('simulink/Sources/In1', [blkPath, '/Mach_In'], ...
        'Position', [50, 400, 80, 420], 'Port', '1');
    add_block('simulink/Sources/In1', [blkPath, '/AoA_In'], ...
        'Position', [50, 450, 80, 470], 'Port', '2');

    add_block('simulink/Lookup Tables/2-D Lookup Table', [blkPath, '/CD_LUT'], ...
        'Position', [180, 390, 300, 440], ...
        'Table', 'CD_table', ...
        'BreakpointsForDimension1', 'mach_bp', ...
        'BreakpointsForDimension2', 'aoa_bp', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Mach_In/1', 'CD_LUT/1');
    add_line(blkPath, 'AoA_In/1', 'CD_LUT/2');

    % -- 2-D CN Lookup --
    add_block('simulink/Lookup Tables/2-D Lookup Table', [blkPath, '/CN_LUT'], ...
        'Position', [180, 460, 300, 510], ...
        'Table', 'CN_table', ...
        'BreakpointsForDimension1', 'mach_bp', ...
        'BreakpointsForDimension2', 'aoa_bp', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Mach_In/1', 'CN_LUT/1');
    add_line(blkPath, 'AoA_In/1', 'CN_LUT/2');

    % -- 2-D Cm Lookup --
    add_block('simulink/Lookup Tables/2-D Lookup Table', [blkPath, '/Cm_LUT'], ...
        'Position', [180, 530, 300, 580], ...
        'Table', 'Cm_table', ...
        'BreakpointsForDimension1', 'mach_bp', ...
        'BreakpointsForDimension2', 'aoa_bp', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Mach_In/1', 'Cm_LUT/1');
    add_line(blkPath, 'AoA_In/1', 'Cm_LUT/2');

    % -- 2-D Croll Lookup --
    add_block('simulink/Lookup Tables/2-D Lookup Table', [blkPath, '/Croll_LUT'], ...
        'Position', [180, 600, 300, 650], ...
        'Table', 'Croll_table', ...
        'BreakpointsForDimension1', 'mach_bp', ...
        'BreakpointsForDimension2', 'aoa_bp', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Mach_In/1', 'Croll_LUT/1');
    add_line(blkPath, 'AoA_In/1', 'Croll_LUT/2');

    % -- Output Ports --
    outports = {'Thrust', 'Mass', 'Ixx', 'Iyy', 'Izz', 'CG_x', 'CD', 'CN', 'Cm', 'Croll'};
    sources = {'Thrust_LUT', 'Mass_LUT', 'Ixx_LUT', 'Iyy_LUT', 'Izz_LUT', 'CG_LUT', ...
               'CD_LUT', 'CN_LUT', 'Cm_LUT', 'Croll_LUT'};
    for i = 1:numel(outports)
        portNum = num2str(i);
        add_block('simulink/Sinks/Out1', [blkPath, '/', outports{i}, '_Out'], ...
            'Position', [380, 30 + 60*(i-1), 410, 50 + 60*(i-1)], ...
            'Port', portNum);
        add_line(blkPath, [sources{i}, '/1'], [outports{i}, '_Out/1']);
    end

    %% Set up the mask
    maskObj = Simulink.Mask.create(blkPath);
    maskObj.Display = sprintf(['color(''blue'');\n', ...
        'disp(''ORK Plant'');\n', ...
        'port_label(''input'', 1, ''Mach'');\n', ...
        'port_label(''input'', 2, ''AoA'');\n', ...
        'port_label(''output'', 1, ''Thrust [N]'');\n', ...
        'port_label(''output'', 2, ''Mass [kg]'');\n', ...
        'port_label(''output'', 3, ''Ixx'');\n', ...
        'port_label(''output'', 4, ''Iyy'');\n', ...
        'port_label(''output'', 5, ''Izz'');\n', ...
        'port_label(''output'', 6, ''CG_x [m]'');\n', ...
        'port_label(''output'', 7, ''CD'');\n', ...
        'port_label(''output'', 8, ''CN'');\n', ...
        'port_label(''output'', 9, ''Cm'');\n', ...
        'port_label(''output'', 10, ''Croll'');\n']);

    % Add mask parameters
    maskObj.addParameter('Type', 'edit', 'Name', 'ork_file_path', ...
        'Prompt', 'ORK file path:', 'Value', '''rocket.ork''');
    maskObj.addParameter('Type', 'edit', 'Name', 'sim_index', ...
        'Prompt', 'Simulation index (0-based):', 'Value', '0');
    maskObj.addParameter('Type', 'edit', 'Name', 'mach_max', ...
        'Prompt', 'Max Mach for CD table:', 'Value', '3.0');
    maskObj.addParameter('Type', 'edit', 'Name', 'aoa_max_deg', ...
        'Prompt', 'Max AoA [deg] for CD table:', 'Value', '15.0');
    maskObj.addParameter('Type', 'checkbox', 'Name', 'enable_validation', ...
        'Prompt', 'Run OR simulation for validation', 'Value', 'off');

    % Mask initialization callback
    maskObj.Initialization = sprintf([...
        '%% ORK Plant Loader — mask init callback\n', ...
        '%% This runs when the model is loaded or the mask is applied.\n', ...
        'ork_data = ork_import(eval(ork_file_path), ...\n', ...
        '    ''SimIndex'', str2double(sim_index), ...\n', ...
        '    ''MachMax'', str2double(mach_max), ...\n', ...
        '    ''AoAMax'', str2double(aoa_max_deg), ...\n', ...
        '    ''RunSim'', strcmp(enable_validation, ''on''));\n', ...
        '\n', ...
        '%% Assign to mask workspace\n', ...
        'thrust_time = ork_data.thrust_time;\n', ...
        'thrust_force = ork_data.thrust_force;\n', ...
        'mass_time = ork_data.mass_time;\n', ...
        'mass_total = ork_data.mass_total;\n', ...
        'mass_propellant = ork_data.mass_propellant;\n', ...
        'Ixx_vs_time = ork_data.Ixx_vs_time;\n', ...
        'Iyy_vs_time = ork_data.Iyy_vs_time;\n', ...
        'Izz_vs_time = ork_data.Izz_vs_time;\n', ...
        'cg_x_vs_time = ork_data.cg_x_vs_time;\n', ...
        'mach_bp = ork_data.mach_bp;\n', ...
        'aoa_bp = ork_data.aoa_bp;\n', ...
        'CD_table = ork_data.CD_table;\n', ...
        'CN_table = ork_data.CN_table;\n', ...
        'Cm_table = ork_data.Cm_table;\n', ...
        'Croll_table = ork_data.Croll_table;\n', ...
        'ref_area = ork_data.ref_area;\n', ...
        'ref_length = ork_data.ref_length;\n', ...
        'burn_time = ork_data.burn_time;\n']);

    maskObj.Description = sprintf([...
        'ORK Plant Loader\n\n', ...
        'Automatically imports an OpenRocket .ork file and populates\n', ...
        'lookup tables for thrust, mass, inertia, and aerodynamic\n', ...
        'coefficients (CD, CN, Cm, Croll) as functions of time,\n', ...
        'Mach number, and angle of attack.\n\n', ...
        'Inputs: Mach, AoA (rad)\n', ...
        'Outputs: Thrust, Mass, Ixx-Izz, CG_x, CD, CN, Cm, Croll\n\n', ...
        'Requires ork-exporter.jar and Java 17+.']);

    %% Save the library
    save_system(modelName);
    fprintf('Created Simulink library: %s.slx\n', modelName);
    fprintf('Block: %s\n', blkPath);
    fprintf('\nTo use:\n');
    fprintf('  1. Copy the block into your model\n');
    fprintf('  2. Set the .ork file path in the mask\n');
    fprintf('  3. Connect Mach and AoA inputs\n');
    fprintf('  4. Connect outputs to your 6-DOF plant\n');
end
