function ork_create_plant_block(modelName)
%ORK_CREATE_PLANT_BLOCK  Create a masked Simulink library block for OR import.
%
%   ORK_CREATE_PLANT_BLOCK() creates a new Simulink library 'ork_plant_lib'
%   containing a masked subsystem that automatically imports .ork data.
%
%   ORK_CREATE_PLANT_BLOCK(MODELNAME) uses the specified library name.
%
%   The masked block provides these mask parameters:
%     - ork_file_path: Path to the .ork file
%     - sim_index: Simulation index (0-based, default 0)
%     - mach_max, aoa_max_deg: Aero table extents
%     - alt_max, alt_step: Altitude table extents [m] (v2.1)
%     - aero_model: Aero model ('auto' or 'barrowman')
%     - enable_validation: Run OR sim for comparison
%
%   The mask initialization callback calls ork_import() and populates the
%   mask workspace. The block's output ports expose the imported data via
%   lookup tables.
%
%   v2.1 changes:
%     - All aero LUTs are n-D (Mach × AoA × Altitude) instead of 2-D
%     - New input port: Altitude (port 3)
%     - New mask parameters: alt_max, alt_step
%     - alt_bp assigned in mask workspace
%     - I_tensor_vs_time assigned in mask workspace
%     - Motor identity fields assigned in mask workspace
%
%   Usage:
%     1. Run this script to create the library
%     2. Copy the 'ORK Plant Loader' block into your model
%     3. Double-click the block and set the .ork file path
%     4. Run your simulation - data loads automatically
%
%   See also: ork_import, ork_setup_plant, ork_update_plant_data

    if nargin < 1
        modelName = 'ork_plant_lib';
    end

    %% Create the library
    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end
    new_system(modelName, 'Library');
    open_system(modelName);

    %% Create the masked subsystem
    blkPath = [modelName, '/ORK Plant Loader'];
    add_block('simulink/Ports & Subsystems/Subsystem', blkPath);

    % Remove default content
    delete_line(blkPath, 'In1/1', 'Out1/1');
    delete_block([blkPath, '/In1']);
    delete_block([blkPath, '/Out1']);

    %% Add input ports
    add_block('simulink/Sources/Clock', [blkPath, '/Clock'], ...
        'Position', [50, 30, 90, 50]);

    add_block('simulink/Sources/In1', [blkPath, '/Mach_In'], ...
        'Position', [50, 400, 80, 420], 'Port', '1');
    add_block('simulink/Sources/In1', [blkPath, '/AoA_In'], ...
        'Position', [50, 450, 80, 470], 'Port', '2');
    add_block('simulink/Sources/In1', [blkPath, '/Alt_In'], ...
        'Position', [50, 500, 80, 520], 'Port', '3');

    %% ── 1-D Lookup Tables (time-based) ──

    % Thrust (time -> N)
    add_block('simulink/Lookup Tables/1-D Lookup Table', [blkPath, '/Thrust_LUT'], ...
        'Position', [180, 20, 280, 60], ...
        'Table', 'thrust_force', ...
        'BreakpointsForDimension1', 'thrust_time', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Clock/1', 'Thrust_LUT/1');

    % Mass (time -> kg)
    add_block('simulink/Lookup Tables/1-D Lookup Table', [blkPath, '/Mass_LUT'], ...
        'Position', [180, 80, 280, 120], ...
        'Table', 'mass_total', ...
        'BreakpointsForDimension1', 'mass_time', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Clock/1', 'Mass_LUT/1');

    % Ixx, Iyy, Izz
    moiNames = {'Ixx', 'Iyy', 'Izz'};
    moiVars  = {'Ixx_vs_time', 'Iyy_vs_time', 'Izz_vs_time'};
    for k = 1:3
        yPos = 140 + (k-1)*60;
        add_block('simulink/Lookup Tables/1-D Lookup Table', ...
            [blkPath, '/', moiNames{k}, '_LUT'], ...
            'Position', [180, yPos, 280, yPos+40], ...
            'Table', moiVars{k}, ...
            'BreakpointsForDimension1', 'mass_time', ...
            'InterpMethod', 'Linear point-slope', ...
            'ExtrapMethod', 'Clip');
        add_line(blkPath, 'Clock/1', [moiNames{k}, '_LUT/1']);
    end

    % dI/dt
    dmoiNames = {'dIxx', 'dIyy', 'dIzz'};
    dmoiVars  = {'dIxx_dt', 'dIyy_dt', 'dIzz_dt'};
    for k = 1:3
        yPos = 140 + (k-1)*60;
        add_block('simulink/Lookup Tables/1-D Lookup Table', ...
            [blkPath, '/', dmoiNames{k}, '_LUT'], ...
            'Position', [380, yPos, 480, yPos+40], ...
            'Table', dmoiVars{k}, ...
            'BreakpointsForDimension1', 'mass_time', ...
            'InterpMethod', 'Linear point-slope', ...
            'ExtrapMethod', 'Clip');
        add_line(blkPath, 'Clock/1', [dmoiNames{k}, '_LUT/1']);
    end

    % CG
    add_block('simulink/Lookup Tables/1-D Lookup Table', [blkPath, '/CG_LUT'], ...
        'Position', [180, 320, 280, 360], ...
        'Table', 'cg_x_vs_time', ...
        'BreakpointsForDimension1', 'mass_time', ...
        'InterpMethod', 'Linear point-slope', ...
        'ExtrapMethod', 'Clip');
    add_line(blkPath, 'Clock/1', 'CG_LUT/1');

    %% ── n-D Aero Lookup Tables (Mach × AoA × Altitude) ──
    % v2.1: Upgraded from 2-D to n-D for altitude-dependent aero
    aeroNames = {'CD', 'CN', 'Cm', 'Croll', 'CrollDamp', 'CrollForce'};
    aeroVars  = {'CD_table', 'CN_table', 'Cm_table', 'Croll_table', ...
                 'CrollDamp_table', 'CrollForce_table'};
    for k = 1:numel(aeroNames)
        yPos = 390 + (k-1)*70;
        blkName = [aeroNames{k}, '_LUT'];
        add_block('simulink/Lookup Tables/n-D Lookup Table', ...
            [blkPath, '/', blkName], ...
            'Position', [180, yPos, 300, yPos+50], ...
            'NumberOfTableDimensions', '3', ...
            'Table', aeroVars{k}, ...
            'BreakpointsForDimension1', 'mach_bp', ...
            'BreakpointsForDimension2', 'aoa_bp', ...
            'BreakpointsForDimension3', 'alt_bp', ...
            'InterpMethod', 'Linear point-slope', ...
            'ExtrapMethod', 'Clip');
        add_line(blkPath, 'Mach_In/1', [blkName, '/1']);
        add_line(blkPath, 'AoA_In/1',  [blkName, '/2']);
        add_line(blkPath, 'Alt_In/1',  [blkName, '/3']);
    end

    %% ── Output Ports ──
    outports = {'Thrust', 'Mass', 'Ixx', 'Iyy', 'Izz', ...
                'dIxx_dt', 'dIyy_dt', 'dIzz_dt', ...
                'CG_x', 'CD', 'CN', 'Cm', 'Croll', 'CrollDamp', 'CrollForce'};
    sources = {'Thrust_LUT', 'Mass_LUT', 'Ixx_LUT', 'Iyy_LUT', 'Izz_LUT', ...
               'dIxx_LUT', 'dIyy_LUT', 'dIzz_LUT', ...
               'CG_LUT', 'CD_LUT', 'CN_LUT', 'Cm_LUT', 'Croll_LUT', ...
               'CrollDamp_LUT', 'CrollForce_LUT'};
    for i = 1:numel(outports)
        portNum = num2str(i);
        add_block('simulink/Sinks/Out1', [blkPath, '/', outports{i}, '_Out'], ...
            'Position', [580, 30 + 50*(i-1), 610, 50 + 50*(i-1)], ...
            'Port', portNum);
        add_line(blkPath, [sources{i}, '/1'], [outports{i}, '_Out/1']);
    end

    %% Set up the mask
    maskObj = Simulink.Mask.create(blkPath);
    maskObj.Display = sprintf([...
        'color(''blue'');\n', ...
        'disp(''ORK Plant v2.1'');\n', ...
        'port_label(''input'', 1, ''Mach'');\n', ...
        'port_label(''input'', 2, ''AoA [rad]'');\n', ...
        'port_label(''input'', 3, ''Alt [m]'');\n', ...
        'port_label(''output'', 1, ''Thrust [N]'');\n', ...
        'port_label(''output'', 2, ''Mass [kg]'');\n', ...
        'port_label(''output'', 3, ''Ixx'');\n', ...
        'port_label(''output'', 4, ''Iyy'');\n', ...
        'port_label(''output'', 5, ''Izz'');\n', ...
        'port_label(''output'', 6, ''dIxx/dt'');\n', ...
        'port_label(''output'', 7, ''dIyy/dt'');\n', ...
        'port_label(''output'', 8, ''dIzz/dt'');\n', ...
        'port_label(''output'', 9, ''CG_x [m]'');\n', ...
        'port_label(''output'', 10, ''CD'');\n', ...
        'port_label(''output'', 11, ''CN'');\n', ...
        'port_label(''output'', 12, ''Cm'');\n', ...
        'port_label(''output'', 13, ''Croll'');\n', ...
        'port_label(''output'', 14, ''CrollDamp'');\n', ...
        'port_label(''output'', 15, ''CrollForce'');\n']);

    % Mask parameters
    maskObj.addParameter('Type', 'edit', 'Name', 'ork_file_path', ...
        'Prompt', 'ORK file path:', 'Value', '''rocket.ork''');
    maskObj.addParameter('Type', 'edit', 'Name', 'sim_index', ...
        'Prompt', 'Simulation index (0-based):', 'Value', '0');
    maskObj.addParameter('Type', 'edit', 'Name', 'mach_max', ...
        'Prompt', 'Max Mach for aero table:', 'Value', '3.0');
    maskObj.addParameter('Type', 'edit', 'Name', 'aoa_max_deg', ...
        'Prompt', 'Max AoA [deg] for aero table:', 'Value', '15.0');
    maskObj.addParameter('Type', 'edit', 'Name', 'alt_max', ...
        'Prompt', 'Max altitude [m] for aero table:', 'Value', '5000');
    maskObj.addParameter('Type', 'edit', 'Name', 'alt_step', ...
        'Prompt', 'Altitude step [m] for aero table:', 'Value', '500');
    maskObj.addParameter('Type', 'popup', 'Name', 'aero_model', ...
        'Prompt', 'Aero model:', 'Value', 'auto', ...
        'TypeOptions', {{'auto', 'barrowman'}});
    maskObj.addParameter('Type', 'checkbox', 'Name', 'enable_validation', ...
        'Prompt', 'Run OR simulation for validation', 'Value', 'off');

    % Mask initialization callback
    maskObj.Initialization = sprintf([...
        '%% ORK Plant Loader v2.1 - mask init callback\n', ...
        '%% This runs when the model is loaded or the mask is applied.\n', ...
        'ork_data = ork_import(eval(ork_file_path), ...\n', ...
        '    ''SimIndex'', str2double(sim_index), ...\n', ...
        '    ''MachMax'', str2double(mach_max), ...\n', ...
        '    ''AoAMax'', str2double(aoa_max_deg), ...\n', ...
        '    ''AltMax'', str2double(alt_max), ...\n', ...
        '    ''AltStep'', str2double(alt_step), ...\n', ...
        '    ''AeroModel'', aero_model, ...\n', ...
        '    ''RunSim'', strcmp(enable_validation, ''on''));\n', ...
        '\n', ...
        '%% Assign to mask workspace\n', ...
        'thrust_time = ork_data.thrust_time;\n', ...
        'thrust_force = ork_data.thrust_force;\n', ...
        'mass_time = ork_data.mass_time;\n', ...
        'mass_total = ork_data.mass_total;\n', ...
        'mass_propellant = ork_data.mass_propellant;\n', ...
        'Ixx_vs_time = ork_data.Ixx_vs_time;\n', ...
        'Iyy_vs_time = ork_data.Iyy_vs_time;\n', ...
        'Izz_vs_time = ork_data.Izz_vs_time;\n', ...
        'dIxx_dt = ork_data.dIxx_dt;\n', ...
        'dIyy_dt = ork_data.dIyy_dt;\n', ...
        'dIzz_dt = ork_data.dIzz_dt;\n', ...
        'cg_x_vs_time = ork_data.cg_x_vs_time;\n', ...
        'mach_bp = ork_data.mach_bp;\n', ...
        'aoa_bp = ork_data.aoa_bp;\n', ...
        'alt_bp = ork_data.alt_bp;\n', ...
        'CD_table = ork_data.CD_table;\n', ...
        'CN_table = ork_data.CN_table;\n', ...
        'Cm_table = ork_data.Cm_table;\n', ...
        'Croll_table = ork_data.Croll_table;\n', ...
        'CrollDamp_table = ork_data.CrollDamp_table;\n', ...
        'CrollForce_table = ork_data.CrollForce_table;\n', ...
        'ref_area = ork_data.ref_area;\n', ...
        'ref_length = ork_data.ref_length;\n', ...
        'burn_time = ork_data.burn_time;\n']);

    maskObj.Description = sprintf([...
        'ORK Plant Loader v2.1\n\n', ...
        'Automatically imports an OpenRocket .ork file and populates\n', ...
        'n-D lookup tables for thrust, mass, inertia (with dI/dt), and\n', ...
        'aerodynamic coefficients (CD, CN, Cm, Croll, CrollDamp,\n', ...
        'CrollForce) as functions of Mach × AoA × Altitude.\n\n', ...
        'Coordinate convention: OpenRocket body frame.\n', ...
        'Use ork_coord_transforms() to convert to Aerospace Blockset.\n\n', ...
        'Inputs: Mach, AoA [rad], Altitude [m]\n', ...
        'Outputs: Thrust, Mass, Ixx-Izz, dIxx-dIzz/dt, CG_x,\n', ...
        '         CD, CN, Cm, Croll, CrollDamp, CrollForce\n\n', ...
        'Requires ork-exporter.jar and Java 17+.']);

    %% Save the library
    save_system(modelName);
    fprintf('Created Simulink library: %s.slx\n', modelName);
    fprintf('Block: %s\n', blkPath);
    fprintf('\nTo use:\n');
    fprintf('  1. Copy the block into your model\n');
    fprintf('  2. Set the .ork file path in the mask\n');
    fprintf('  3. Connect Mach, AoA, and Altitude inputs\n');
    fprintf('  4. Connect outputs to your 6-DOF plant\n');
    fprintf('\nTo update data without regenerating block:\n');
    fprintf('  ork_update_plant_data(''my_model'', ''rocket.ork'')\n');
end
